name: Docker Image CI-CD-flask1

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:

  build-image:
    name: test-app-flask
    runs-on: self-hosted
    
    env:
      IMAGE_NAME: azurecontainerswebsite
      IMAGE_TAG: ${{github.run_id}}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
